packages:
  - gitdot-web
  - gitdot-api-ts

catalog:
  "@biomejs/biome": "2.3.11"
  "@types/jest": "^30.0.0"
  "@types/node": "^20"
  "lint-staged": "^16.2.7"
  "ts-jest": "^29.4.6"
  "ts-node": "^10.9.2"
  "tw-animate-css": "^1.4.0"
  "typescript": "^5"
  "zod": "^4.3.5"
